# Web Scraping Assignment - 4

In [1]:
# Importing Libraries
import selenium
import pandas as pd
import time
from bs4 import BeautifulSoup

# Importing selenium webdriver 
from selenium import webdriver
import warnings
warnings.filterwarnings('ignore')

# Importing required Exceptions which needs to handled
from selenium.common.exceptions import StaleElementReferenceException, NoSuchElementException
from selenium.webdriver.common.by import By
#Importing requests
import requests

# importing regex
import re

1. Scrape the details of most viewed videos on YouTube from Wikipedia.
Url = https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos

You need to find following details:

A) Rank

B) Name

C) Artist

D) Upload date

E) Views

In [2]:
# Connecting to the webdriver
driver=webdriver.Chrome(r"C:\Chrome driver\Chromedriver.exe")

In [4]:
# Getting the webpage of mentioned url 
driver.get('https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos')

In [5]:
#creating empty list
Rank=[]
Name=[]
Artist=[]
Upload_date=[]
Views=[]

In [6]:
#Scraping data of rank details
try:
    for i in driver.find_elements(By.XPATH,'//table[@class="wikitable sortable jquery-tablesorter"]//tbody//tr//td[1]')[:30]:
        Rank.append(i.text)
except NoSuchElementException:
    Rank.append('-')
        

#Scraping data of video names
try:
    for i in driver.find_elements(By.XPATH,'//table[@class="wikitable sortable jquery-tablesorter"]//tbody//tr//td[2]')[:30]:
        Name.append(i.text)
except NoSuchElementException:
    Name.append('-')

#Scraping data of artist name
try:
    for i in driver.find_elements(By.XPATH,'//table[@class="wikitable sortable jquery-tablesorter"]//tbody//tr//td[3]')[:30]:
        Artist.append(i.text)
except NoSuchElementException:        
    Artist.append('-')
    
#Scraping data of upload dates
try:
    for i in driver.find_elements(By.XPATH,'//table[@class="wikitable sortable jquery-tablesorter"]//tbody//tr//td[5]')[:30]:
        Upload_date.append(i.text)
except NoSuchElementException:        
    Upload_date.append('-')
    
    
#Scraping data of views
try:
    for i in driver.find_elements(By.XPATH,'//table[@class="wikitable sortable jquery-tablesorter"]//tbody//tr//td[4]')[:30]:
        Views.append(i.text)
except NoSuchElementException:
    Views.append('-')

In [7]:
#DATA FRAMEING
Youtube=pd.DataFrame({})
Youtube['Rank'] = Rank
Youtube['Name'] = Name
Youtube['Artist'] = Artist
Youtube['Uploaded Date'] = Upload_date
Youtube['Views'] = Views

In [8]:
#Printing data frame
Youtube

,Rank,Name,Artist,Uploaded Date,Views
0,1.,"""Baby Shark Dance""[3]",Pinkfong Baby Shark - Kids' Songs & Stories,"June 17, 2016",11.40
1,2.,"""Despacito""[6]",Luis Fonsi,"January 12, 2017",7.98
2,3.,"""Johny Johny Yes Papa""[12]",LooLoo Kids,"October 8, 2016",6.47
3,4.,"""Shape of You""[13]",Ed Sheeran,"January 30, 2017",5.81
4,5.,"""See You Again""[15]",Wiz Khalifa,"April 6, 2015",5.64
5,6.,"""Bath Song""[20]",Cocomelon – Nursery Rhymes,"May 2, 2018",5.63
6,7.,"""Phonics Song with Two Words""[21]",ChuChu TV,"March 6, 2014",4.90
7,8.,"""Uptown Funk""[22]",Mark Ronson,"November 19, 2014",4.70
8,9.,"""Learning Colors – Colorful Eggs on a Farm""[23]",Miroshka TV,"February 27, 2018",4.65
9,10.,"""Gangnam Style""[24]",Psy,"July 15, 2012",4.55
10,11.,"""Masha and the Bear – Recipe for Disaster""[29]",Get Movies,"January 31, 2012",4.51
11,12.,"""Wheels on the Bus""[30]",Cocomelon – Nursery Rhymes,"May 24, 2018",4.40
12,13.,"""Dame Tu Cosita""[31]",El Chombo,"April 5, 2018",4.07
13,14.,"""Sugar""[32]",Maroon 5,"January 14, 2015",3.76
14,15.,"""Roar""[33]",Katy Perry,"September 5, 2013",3.66
15,16.,"""Counting Stars""[34]",OneRepublic,"May 31, 2013",3.65
16,17.,"""Sorry""[35]",Justin Bieber,"October 22, 2015",3.59
17,18.,"""Axel F""[36]",Crazy Frog,"June 16, 2009",3.52
18,18.,"""Thinking Out Loud""[37]",Ed Sheeran,"October 7, 2014",3.50
19,20.,"""Baa Baa Black Sheep""[38]",Cocomelon – Nursery Rhymes,"June 25, 2018",3.38
20,21.,"""Dark Horse""[39]",Katy Perry,"February 20, 2014",3.35
21,22.,"""Faded""[40]",Alan Walker,"December 3, 2015",3.34
22,23.,"""Girls Like You""[41]",Maroon 5,"May 31, 2018",3.33
23,24.,"""Let Her Go""[42]",Passenger,"July 25, 2012",3.30
24,25.,"""Bailando""[43]",Enrique Iglesias,"April 11, 2014",3.27
25,26.,"""Lean On""[44]",Major Lazer,"March 22, 2015",3.26
26,27.,"""Perfect""[45]",Ed Sheeran,"November 9, 2017",3.26
27,28.,"""Waka Waka (This Time for Africa)""[46]",Shakira,"June 4, 2010",3.25
28,29.,"""Shake It Off""[47]",Taylor Swift,"August 18, 2014",3.21
29,30.,"""Humpty the train on a fruits ride""[48]",Kiddiestv Hindi – Nursery Rhymes & Kids Songs,"January 26, 2018",3.17

In [10]:
driver.close()

2.Scrape the details team India’s international fixtures from bcci.tv.
Url = https://www.bcci.tv/.

You need to find following details:

A) Match title (I.e. 1 st ODI)

B) Series

C) Place

D) Date

E) Time

Note: - From bcci.tv home page you have reach to the international fixture page through code.

In [11]:
# Connecting to the webdriver
driver=webdriver.Chrome(r"C:\Chrome driver\Chromedriver.exe")

In [12]:
# Getting the webpage of mentioned url 
driver.get("https://www.bcci.tv/")

In [13]:
#going to international fixtures page
International = driver.find_element(By.XPATH,'/html/body/nav/div[1]/div[2]/ul[1]/li[2]/a') 
International.click()

In [14]:
#Creating Empty List
Name=[]
Series=[]
Place=[]
Date=[]
Time=[]

#Scrapping Name
try:
    for i in driver.find_elements(By.XPATH,'//span[@class="matchOrderText ng-binding ng-scope"]'):
        Name.append(i.text.replace('-',""))
except NoSuchElementException:
    Name.append('-')

#Scrapping Series
try:
    
    for i in driver.find_elements(By.XPATH,'//span[@class="ng-binding"]'):
        Series.append(i.text)
except NoSuchElementException:
    Series.append('-')
    
#scrapping Place
try:
    for i in driver.find_elements(By.XPATH,'//span[@class="ng-binding ng-scope"]'):
        Place.append(i.text)
except NoSuchElementException:
    Place.append('-')
    
#Scrapping Date
try:
    for i in driver.find_elements(By.XPATH,'//h5[@class="ng-binding"]'):
        Date.append(i.text)
except NoSuchElementException:
    Date.append('-')
    
#Scrapping Time
try:
    for i in driver.find_elements(By.XPATH,'//h5[@class="text-right ng-binding"]'):
        Time.append(i.text.replace('IST',""))
except NoSuchElementException:
    Time.append('-')

    
# Creating Dataframe

Int_Fixtures=pd.DataFrame({})

Int_Fixtures['Match Title']=Name
Int_Fixtures['Series']=Series
Int_Fixtures['Place']=Place
Int_Fixtures['Date']=Date
Int_Fixtures['Time']=Time
Int_Fixtures

,Match Title,Series,Place,Date,Time
0,1st T20I,ASIA CUP WOMENS 2022,"Sylhet Outer Cricket Stadium,",1 OCT 2022,1:00 PM
1,2nd T20I,SOUTH AFRICA TOUR OF INDIA T20 SERIES 2022-23,"Barsapara Cricket Stadium,",2 OCT 2022,7:00 PM
2,2nd T20I,ASIA CUP WOMENS 2022,"Sylhet Outer Cricket Stadium,",3 OCT 2022,1:00 PM
3,3rd T20I,ASIA CUP WOMENS 2022,"Sylhet Outer Cricket Stadium,",4 OCT 2022,1:00 PM
4,3rd T20I,SOUTH AFRICA TOUR OF INDIA T20 SERIES 2022-23,"Holkar Cricket Stadium,",4 OCT 2022,7:00 PM
5,1st ODI,SOUTH AFRICA TOUR OF INDIA ODI SERIES 2022-23,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,6 OCT 2022,1:30 PM
6,4th T20I,ASIA CUP WOMENS 2022,"Sylhet International Cricket Stadium,",7 OCT 2022,1:00 PM
7,5th T20I,ASIA CUP WOMENS 2022,"Sylhet International Cricket Stadium,",8 OCT 2022,1:00 PM

In [15]:
driver.close()

# 3.Scrape the details of selenium exception from guru99.com.\

Url = https://www.guru99.com/

You need to find following details:

A) Name

B) Description

Note: - From guru99 home page you have to reach to selenium exception handling page through code

In [20]:
# Connecting to the webdriver
driver=webdriver.Chrome(r"C:\Chrome driver\Chromedriver.exe")
driver.maximize_window()

In [22]:
# Getting the webpage of mentioned url 
driver.get("https://www.guru99.com/")
driver.find_element(By.XPATH,'/html/body/div[1]/div/div/div/main/div/article/div/div[1]/div[2]/div[1]/div/ul[1]/li[3]/a').click()

driver.find_element(By.XPATH,'/html/body/div[1]/div/div/div/main/div/article/div/div/table[5]/tbody/tr[34]/td[1]/a/strong').click()
time.sleep(5)

In [30]:
Name=[]
Description=[]

guru99=driver.find_elements(By.XPATH,'//p//strong')
for i in guru99:
    Name.append(i.text)


    guru99=driver.find_elements(By.XPATH,'//div[@class="entry-content single-content"]//p')
for i in guru99:
    Description.append(i.text)

Name=[]
Description=[]

guru99=driver.find_elements(By.XPATH,'//p//strong')
for i in guru99:
    Name.append(i.text)


guru99=driver.find_elements(By.XPATH,'//div[@class="entry-content single-content"]//p')
for i in guru99:
    Description.append(i.text)


Desc=[]
for i in range(2,43):
    Desc.append(Description[i].split(':')[1])


Data={'Name':Name[1:42],'Description':Desc}

df=pd.DataFrame(Data)

df

,Name,Description
0,1. ElementNotVisibleException:,This type of Selenium exception occurs when a...
1,2. ElementNotSelectableException:,This Selenium exception occurs when an elemen...
2,3. NoSuchElementException:,This Exception occurs if an element could not...
3,4. NoSuchFrameException:,This Exception occurs if the frame target to ...
4,5. NoAlertPresentException:,This Exception occurs when you switch to no p...
5,6. NoSuchWindowException:,This Exception occurs if the window target to...
6,7. StaleElementReferenceException:,This Selenium exception occurs happens when t...
7,8. SessionNotFoundException:,The WebDriver is acting after you quit the br...
8,9. TimeoutException:,Thrown when there is not enough time for a co...
9,10. WebDriverException:,This Exception takes place when the WebDriver...
10,11. ConnectionClosedException:,This type of Exception takes place when there...
11,12. ElementClickInterceptedException:,The command may not be completed as the eleme...
12,13. ElementNotInteractableException:,This Selenium exception is thrown when any el...
13,14. ErrorInResponseException:,This happens while interacting with the Firef...
14,15. ErrorHandler.UnknownServerException:,Exception is used as a placeholder in case if...
15,16. ImeActivationFailedException:,This expectation will occur when IME engine a...
16,17. ImeNotAvailableException:,It takes place when IME support is unavailable.
17,18. InsecureCertificateException:,Navigation made the user agent to hit a certi...
18,19. InvalidArgumentException:,It occurs when an argument does not belong to...
19,20. InvalidCookieDomainException:,This happens when you try to add a cookie und...
20,21. InvalidCoordinatesException:,This type of Exception matches an interacting...
21,22. InvalidElementStateException:,It occurs when command can’t be finished when...
22,23. InvalidSessionIdException:,This Exception took place when the given sess...
23,24. InvalidSwitchToTargetException:,This occurs when the frame or window target t...
24,25. JavascriptException:,This issue occurs while executing JavaScript ...
25,26. JsonException:,It occurs when you afford to get the session ...
26,27. NoSuchAttributeException:,This kind of Exception occurs when the attrib...
27,28. MoveTargetOutOfBoundsException:,It takes place if the target provided to the ...
28,29. NoSuchContextException:,ContextAware does mobile device testing.
29,30. NoSuchCookieException:,This Exception occurs when no cookie matching...
30,31. NotFoundException:,This Exception is a subclass of WebDriverExce...
31,32. RemoteDriverServerException:,This Selenium exception is thrown when the se...
32,33. ScreenshotException:,It is not possible to capture a screen.
33,34. SessionNotCreatedException:,It happens when a new session could not be su...
34,35. UnableToSetCookieException:,This occurs if a driver is unable to set a co...
35,36. UnexpectedTagNameException:,Happens if a support class did not get a web ...
36,37. UnhandledAlertException:,This expectation occurs when there is an aler...
37,38. UnexpectedAlertPresentException:,It occurs when there is the appearance of an ...
38,39. UnknownMethodException:,This Exception happens when the requested com...
39,40. UnreachableBrowserException:,This Exception occurs only when the browser i...
40,41. UnsupportedCommandException:,This occurs when remote WebDriver doesn’t sen...

In [31]:
driver.close()

Q4) Scrape the details of State-wise GDP of India from statisticstime.com.

Url = http://statisticstimes.com/

You have to find following details:

A) Rank

B) State

C) GSDP(19-20)

D) GSDP(18-19)

E) Share(18-19)

F) GDP($ billion)

Note: - From statisticstimes home page you have to reach to economy page through code.

In [10]:
# Connecting to the webdriver
driver=webdriver.Chrome(r"C:\Chrome driver\Chromedriver.exe")
driver.maximize_window()

In [11]:
# Getting the webpage of mentioned url 
driver.get(" http://statisticstimes.com/")

In [12]:
# India's GDP
india=driver.find_element(By.XPATH,"//div[@class='navbar']/div[2]/div/a[3]").get_attribute("href")
driver.get(india)

In [13]:
GDP = driver.find_element(By.XPATH,"//ul[@style = 'list-style-type:none;margin-left:20px;']/li/a").get_attribute('href')
driver.get(GDP)

In [14]:
# Scrapping Details
ranks=[]
states=[]
GSDP_18_19=[]
GSDP_19_20=[]
share_18_19=[]
GDP_in_billion=[]

# Rank
for rank in driver.find_elements(By.XPATH,"//table[@id='table_id']/tbody/tr/td[1]"):
    ranks.append(rank.text)
# States
for state in driver.find_elements(By.XPATH,"//table[@id='table_id']/tbody/tr/td[2]"):
    states.append(state.text)
# GSDP for 19-20
for gsdp in driver.find_elements(By.XPATH,"//table[@id='table_id']/tbody/tr/td[3]"):
    GSDP_19_20.append(gsdp.text)
# GSDP 18-19
for gsdp in driver.find_elements(By.XPATH,"//table[@id='table_id']/tbody/tr/td[4]"):
    GSDP_18_19.append(gsdp.text)      
# Share    
for share in driver.find_elements(By.XPATH,"//table[@id='table_id']/tbody/tr/td[5]"):
    share_18_19.append(share.text)    
# GDP in $ billion
for gdp in driver.find_elements(By.XPATH,"//table[@id='table_id']/tbody/tr/td[6]"):
    GDP_in_billion.append(gdp.text)

In [15]:
df=pd.DataFrame({})
df["Rank"]=ranks
df["State"]=states
df["GSDP(19-20)"]=GSDP_19_20
df["GSDP(18-19)"]=GSDP_18_19
df["Share(18-19)"]=share_18_19
df["GDP($ billion)"]=GDP_in_billion
df

,Rank,State,GSDP(19-20),GSDP(18-19),Share(18-19),GDP($ billion)
0,1,Maharashtra,-,"2,632,792",13.94%,399.921
1,2,Tamil Nadu,"1,845,853","1,630,208",8.63%,247.629
2,3,Uttar Pradesh,"1,687,818","1,584,764",8.39%,240.726
3,4,Gujarat,-,"1,502,899",7.96%,228.290
4,5,Karnataka,"1,631,977","1,493,127",7.91%,226.806
5,6,West Bengal,"1,253,832","1,089,898",5.77%,165.556
6,7,Rajasthan,"1,020,989","942,586",4.99%,143.179
7,8,Andhra Pradesh,"972,782","862,957",4.57%,131.083
8,9,Telangana,"969,604","861,031",4.56%,130.791
9,10,Madhya Pradesh,"906,672","809,592",4.29%,122.977
10,11,Kerala,-,"781,653",4.14%,118.733
11,12,Delhi,"856,112","774,870",4.10%,117.703
12,13,Haryana,"831,610","734,163",3.89%,111.519
13,14,Bihar,"611,804","530,363",2.81%,80.562
14,15,Punjab,"574,760","526,376",2.79%,79.957
15,16,Odisha,"521,275","487,805",2.58%,74.098
16,17,Assam,-,"315,881",1.67%,47.982
17,18,Chhattisgarh,"329,180","304,063",1.61%,46.187
18,19,Jharkhand,"328,598","297,204",1.57%,45.145
19,20,Uttarakhand,-,"245,895",1.30%,37.351
20,21,Jammu & Kashmir,-,"155,956",0.83%,23.690
21,22,Himachal Pradesh,"165,472","153,845",0.81%,23.369
22,23,Goa,"80,449","73,170",0.39%,11.115
23,24,Tripura,"55,984","49,845",0.26%,7.571
24,25,Chandigarh,-,"42,114",0.22%,6.397
25,26,Puducherry,"38,253","34,433",0.18%,5.230
26,27,Meghalaya,"36,572","33,481",0.18%,5.086
27,28,Sikkim,"32,496","28,723",0.15%,4.363
28,29,Manipur,"31,790","27,870",0.15%,4.233
29,30,Nagaland,-,"27,283",0.14%,4.144
30,31,Arunachal Pradesh,-,"24,603",0.13%,3.737
31,32,Mizoram,"26,503","22,287",0.12%,3.385
32,33,Andaman & Nicobar Islands,-,-,-,-

In [16]:
driver.close()

# 5. Scrape the details of trending repositories on Github.com.

Url = https://github.com/

You have to find the following details:

A) Repository title

B) Repository description

C) Contributors count

D) Language used

ASSIGNMENT

Note: - From the home page you have to click on the trending option from Explore menu through code.

In [17]:
# Connecting to the webdriver
driver=webdriver.Chrome(r"C:\Chrome driver\Chromedriver.exe")
driver.maximize_window()

In [18]:
# Getting the webpage of mentioned url 
driver.get('https://github.com/')

In [19]:
#Getting explore button and clicking on it
explore = driver.find_elements(By.XPATH,"/html/body/div[1]/header/div/div[2]/nav/ul/li[4]/details")

In [20]:
#Selecting trending option
trend_url = driver.find_element(By.XPATH,'/html/body/div[1]/header/div/div[2]/div/nav/ul/li[3]/div/ul[3]/li[3]/a')
urls = trend_url.get_attribute("href")
driver.get(urls)

In [21]:
# making empty lists    
repo_urls=[]
Contributors_count=[]
Language_used=[]
repo_title=[]
repo_desc=[]

In [22]:
#scraping repositories urls
repos=driver.find_elements(By.XPATH,'//h1[@class="h3 lh-condensed"]/a')
for i in repos:
    repo_urls.append(i.get_attribute('href'))
time.sleep(2)

In [23]:
repo_urls

['https://github.com/lkwq007/stablediffusion-infinity',
 'https://github.com/TheAlgorithms/C-Plus-Plus',
 'https://github.com/iced-rs/iced',
 'https://github.com/sherlock-project/sherlock',
 'https://github.com/freeCodeCamp/freeCodeCamp',
 'https://github.com/novuhq/novu',
 'https://github.com/github/docs',
 'https://github.com/AUTOMATIC1111/stable-diffusion-webui',
 'https://github.com/firstcontributions/first-contributions',
 'https://github.com/midudev/hacktoberfest-2022',
 'https://github.com/CodeEditApp/CodeEdit',
 'https://github.com/ToolJet/ToolJet',
 'https://github.com/HavocFramework/Havoc',
 'https://github.com/stefanprodan/podinfo',
 'https://github.com/total-typescript/beginners-typescript-tutorial',
 'https://github.com/fineanmol/Hacktoberfest2022',
 'https://github.com/ossamamehmood/Hacktoberfest2022',
 'https://github.com/Aashu-Dubey/React-Native-UI-Templates',
 'https://github.com/yt-dlp/yt-dlp',
 'https://github.com/TryGhost/Ghost',
 'https://github.com/mikeroyal/Steam-Deck-Guide',
 'https://github.com/developedbyed/react-portofolio-with-tailwind',
 'https://github.com/TheAlgorithms/Python',
 'https://github.com/GoVanguard/Getting-into-InfoSec-and-Cybersecurity',
 'https://github.com/freqtrade/freqtrade']

In [24]:
#scraping repositories title
repo_title=[]
try:
    repos=driver.find_elements(By.XPATH,"//h1[@class='h3 lh-condensed']")
    for i in repos:
        repo_title.append(i.text)
except NoSuchElementException:#handling no such element exception
    repo_title.append('No details available')
time.sleep(3)
    
    
for i in repo_urls:
    driver.get(i)
    l=[]
    time.sleep(3)
     #scraping repositories discription
    try:          
        repo_desc.append(driver.find_element(By.XPATH,"/html/body/div[4]/div/main/turbo-frame/div/div/div/div[3]/div[2]/div/div[1]/div/p").text)
    except:
        repo_desc.append('-')
    
    #scraping contributors count
    try:
        count=driver.find_element(By.XPATH,"//h2[@class='h4 mb-3']/a[contains(text(),'Contributors')]/span")
        Contributors_count.append(count.text)
    except NoSuchElementException:#handling no such element exception
        Contributors_count.append('No details available')
    time.sleep(2)
    
     #scraping languages used   
    languages=driver.find_elements(By.XPATH,"//li[@class='d-inline']//a//span[1]")
    if languages:    
        for i in languages:
            l.append(i.text)
    else:
        l.append('No languages used')
    Language_used.append(l)   
    
time.sleep(2)   
#creating dataframe
df=pd.DataFrame({'Title':repo_title,
                'Description':repo_desc,
                'Contributors_count':Contributors_count,
                'Language_used':Language_used})
df

,Title,Description,Contributors_count,Language_used
0,lkwq007 / stablediffusion-infinity,Outpainting with Stable Diffusion on an infini...,3,"[Python, HTML, JavaScript, Jupyter Notebook, S..."
1,TheAlgorithms / C-Plus-Plus,Collection of various algorithms in mathematic...,280,"[C++, CMake]"
2,iced-rs / iced,"A cross-platform GUI library for Rust, inspire...",125,"[Rust, GLSL]"
3,sherlock-project / sherlock,🔎 Hunt down social media accounts by username ...,171,"[Python, Dockerfile]"
4,freeCodeCamp / freeCodeCamp,freeCodeCamp.org's open-source codebase and cu...,"4,550","[TypeScript, JavaScript, CSS, Shell, Dockerfil..."
5,novuhq / novu,⭐ A fully functional real-time notification ce...,115,"[TypeScript, JavaScript, HTML, Handlebars, Doc..."
6,github / docs,The open-source repo for docs.github.com,"1,458","[JavaScript, TypeScript, SCSS]"
7,AUTOMATIC1111 / stable-diffusion-webui,Stable Diffusion web UI,89,"[Python, JavaScript, CSS, Shell, Batchfile]"
8,firstcontributions / first-contributions,🚀✨ Help beginners to contribute to open source...,"3,651",[No languages used]
9,midudev / hacktoberfest-2022,Solving a frontend challenge for Hacktoberfest...,88,"[JavaScript, Astro, TypeScript, CSS, Svelte, Vue]"
10,CodeEditApp / CodeEdit,CodeEdit App for macOS – Elevate your code edi...,71,[Swift]
11,ToolJet / ToolJet,Extensible low-code framework for building bus...,215,"[JavaScript, TypeScript, SCSS, HTML, Shell, EJS]"
12,HavocFramework / Havoc,The Havoc Framework,6,"[Go, C, C++, Ragel, CMake, Ruby]"
13,stefanprodan / podinfo,Go microservice template for Kubernetes,35,"[Go, CUE, HTML, Makefile, Shell, Smarty, Docke..."
14,total-typescript / beginners-typescript-tutorial,An interactive TypeScript tutorial for beginners,12,"[TypeScript, JavaScript]"
15,fineanmol / Hacktoberfest2022,Make your first Pull Request on Hacktoberfest ...,775,"[Java, Python, HTML, JavaScript, CSS, C]"
16,ossamamehmood / Hacktoberfest2022,Hacktoberfest 2022 OPEN FIRST Pull Request - F...,505,"[HTML, Jupyter Notebook, C++, Java, Python, C]"
17,Aashu-Dubey / React-Native-UI-Templates,UI kits built in React-Native & TypeScript.,No details available,"[TypeScript, Java, Objective-C]"
18,yt-dlp / yt-dlp,A youtube-dl fork with additional features and...,"1,025",[Python]
19,TryGhost / Ghost,Turn your audience into a business. Publishing...,413,"[JavaScript, Handlebars, CSS, HTML, XSLT]"
20,mikeroyal / Steam-Deck-Guide,Steam Deck Guide,8,[Shell]
21,developedbyed / react-portofolio-with-tailwind,-,No details available,"[JavaScript, CSS]"
22,TheAlgorithms / Python,All Algorithms implemented in Python,842,[Python]
23,GoVanguard / Getting-into-InfoSec-and-Cybersec...,"A shorter, less intimidating list of infosec r...",5,[No languages used]
24,freqtrade / freqtrade,"Free, open source crypto trading bot",239,"[Python, Jinja, Shell, Jupyter Notebook, Docke..."

In [25]:
driver.close()

Q 6 ) Scrape the details of top 100 songs on billiboard.com. Url = https://www.billboard.com/

You have to find the following details:

A) Song name

B) Artist name

C) Last week rank

D) Peak rank

E) Weeks on board Note: - From the home page you have to click on the charts option then hot 100-page link through code

In [26]:
# Connecting to the webdriver
driver=webdriver.Chrome(r"C:\Chrome driver\Chromedriver.exe")
driver.maximize_window()

In [27]:
driver.get(" https://www.billboard.com/")

In [37]:
option_chart=driver.find_element(By.XPATH,'/html/body/div[3]/header/div/div[2]/div/div/div[2]/div[2]/div/div/nav/ul/li[1]/a')
option_chart.click()

In [38]:
view_chart=driver.find_element(By.XPATH,'/html/body/div[3]/main/div[2]/div[1]/div[1]/div/div/div[3]/a')
view_chart.click()

In [98]:
Name = []
Artist = []
Last_week_rank = []
Peak_rank = []
Weeks_on_board = []

In [112]:
#scraping song names
try:
    names=driver.find_elements(By.XPATH,'//div[@class="o-chart-results-list-row-container"]//h3')
    for i in names:
        Name.append(i.text)
except NoSuchElementException:       
    Name.append('No details available')
time.sleep(2)    
Name=Name[::4][:100]

In [113]:
len(Name)

100

In [110]:
#scraping artist names
try:
    artist=driver.find_elements(By.XPATH,'//li[@class="lrv-u-width-100p"]//span')
    for i in artist:
        Artist.append(i.text)
except NoSuchElementException:     
    Artist.append('-')
time.sleep(2)    
Artist=Artist[::7][:100]

In [111]:
len(Artist)

100

In [114]:
#scraping last week rank of the song
try:
    last_rank=driver.find_elements(By.XPATH,'//li[@class="o-chart-results-list__item // a-chart-color u-width-72 u-width-55@mobile-max u-width-55@tablet-only lrv-u-flex lrv-u-flex-shrink-0 lrv-u-align-items-center lrv-u-justify-content-center lrv-u-border-b-1 u-border-b-0@mobile-max lrv-u-border-color-grey-light u-background-color-white-064@mobile-max u-hidden@mobile-max"]')
    for i in last_rank:
        Last_week_rank.append(i.text)
except NoSuchElementException:      
    Last_week_rank.append('-')
    time.sleep(2)    
Last_week_rank=Last_week_rank[::2][:100]

In [115]:
len(Last_week_rank)

100

In [105]:
#scraping song's peak rank
try:
    peak=driver.find_elements(By.XPATH,'//li[@class="o-chart-results-list__item // a-chart-bg-color a-chart-color u-width-72 u-width-55@mobile-max u-width-55@tablet-only lrv-u-flex lrv-u-flex-shrink-0 lrv-u-align-items-center lrv-u-justify-content-center lrv-u-background-color-grey-lightest lrv-u-border-b-1 u-border-b-0@mobile-max lrv-u-border-color-grey-light u-hidden@mobile-max"]')
    for i in peak:
        Peak_rank.append(i.text)
except NoSuchElementException:       
    Peak_rank.append('-')
time.sleep(2)    
Peak_rank=Peak_rank[1::2][:100]

In [106]:
len(Peak_rank)

100

In [107]:
#scraping number of weeks on board
try:
    weeks=driver.find_elements(By.XPATH,'//li[@class="o-chart-results-list__item // a-chart-color u-width-72 u-width-55@mobile-max u-width-55@tablet-only lrv-u-flex lrv-u-flex-shrink-0 lrv-u-align-items-center lrv-u-justify-content-center lrv-u-border-b-1 u-border-b-0@mobile-max lrv-u-border-color-grey-light u-background-color-white-064@mobile-max u-hidden@mobile-max"]')
    for i in weeks:
        Weeks_on_board.append(i.text)
except NoSuchElementException:       #handling no such element exception
    Weeks_on_board.append('-')
time.sleep(2)    
Weeks_on_board=Weeks_on_board[1::2][:100]

In [108]:
len(Weeks_on_board)

100

In [116]:
df=pd.DataFrame({'Song_Name':Name,
                'Artist_Name':Artist,
                'Last_week_rank':Last_week_rank,
                'Peak':Peak_rank,
                'Weeks_on_chart':Weeks_on_board})
df

,Song_Name,Artist_Name,Last_week_rank,Peak,Weeks_on_chart
0,Bad Habit,Harry Styles,1,1,25
1,I Like You (A Happier Song),Steve Lacy,2,2,12
2,Sunroof,Post Malone Featuring Doja Cat,5,3,16
3,Super Freaky Girl,Nicky Youre & dazy,4,4,17
4,You Proof,Nicki Minaj,3,1,6
...,...,...,...,...,...
95,Where It Ends,Morgan Wallen,98,12,20
96,Backstage Passes,Bailey Zimmerman,93,32,5
97,Snap,EST Gee Featuring Jack Harlow,-,98,1
98,Beat The Odds,Rosa Linn,97,93,4
99,Bad Habit,Lil Tjay,91,36,4

In [117]:
driver.close()

Q 7) Scrape the details of Data science recruiters from naukri.com. Url = https://www.naukri.com/

You have to find the following details:

A) Name

B) Designation

C) Company

D) Skills they hire for

E) Location Note: - From naukri.com homepage click on the recruiters option and the on the search pane type Data science and click on search. All this should be done through code

In [7]:
# Connecting to the webdriver
driver=webdriver.Chrome(r"C:\Chrome driver\Chromedriver.exe")
driver.maximize_window()

In [12]:
# Getting the webpage of mentioned url 
driver.get("https://www.naukri.com/hr-recruiters-consultants")

In [13]:
#clicking on recruiters link
recruiters=driver.find_element(By.XPATH,"//a[@title='Search Recruiters']")
driver.get(recruiters.get_attribute('href'))
time.sleep(1)

In [14]:
#accesing search bar
search=driver.find_element(By.XPATH,"//input[@class='sugInp']")
search.send_keys("Data Science")
time.sleep(1)

In [15]:
#clicking on search button
button=driver.find_element(By.XPATH,"//button[@id='qsbFormBtn']")
button.click()
time.sleep(1)

In [16]:
#Creating empty lists
Name = []
Designation = []
Company = []
Skills = []
Location = []

In [17]:
#Scraping data of Names
for i in driver.find_elements(By.XPATH,"//span[@class='fl ellipsis']"):
    Name.append(i.text)
time.sleep(3)


#Scraping data of Designation

for i in driver.find_elements(By.XPATH,"//span[@class='ellipsis clr']"):
    Designation.append(i.text)
    

#Scraping data of company name

for i in driver.find_elements(By.XPATH,"//div[@class='vcard']//p[1]/a[2]"):
    Company.append(i.text)

    
#Scraping data of locations

for i in driver.find_elements(By.XPATH,"//div[@class='vcard']//p[1]//span"):
    Location.append(i.text)
time.sleep(3)

In [18]:
print(len(Name),len(Designation),len(Company),len(Location))

50 50 50 148

In [19]:
# Creating dataframe 
Naukri=pd.DataFrame({})

Naukri['Name'] = Name
Naukri['Designation'] = Designation
Naukri['Company'] = Company
Naukri['Location'] = Location[:50]
Naukri

,Name,Designation,Company,Location
0,Aakash Harit,HR Manager,Data Science Network,Aakash Harit
1,shravan Kumar Gaddam,Company Recruiter,Shore Infotech India Pvt. Ltd,HR Manager
2,MARSIAN Technologies LLP,Company HR,MARSIAN Technologies LLP,Delhi
3,Anik Agrawal,Company Recruiter,Enerlytics Software Solutions Pvt Ltd,shravan Kumar Gaddam
4,subhas patel,Founder CEO,LibraryXProject,Company Recruiter
5,Abhishek - Only Analytics Hiring - India and,Recruitment Lead Consultant,Apidel Technologies Division of Transpower,Hyderabad / Secunderabad
6,Institute for Financial Management and Resear,Programme Manager,IFMR,MARSIAN Technologies LLP
7,Balu Ramesh,HR Administrator,Techvantage Systems Pvt Ltd,Company HR
8,Asif Lucknowi,Director,Weupskill- Live Wire India,Pune
9,InstaFinancials,Human Resource,CBL Data Science Private Limited,Anik Agrawal
10,Mahesh Babu Channa,HR Team Lead,SocialPrachar.com,Company Recruiter
11,Priyanka Akiri,HR Manager,Infinitive Software Solutions,Ahmedabad
12,Kalpana Dumpala,Executive Hiring,Innominds Software,subhas patel
13,Mubarak,Company HR,MoneyTap,Founder CEO
14,Kushal Rastogi,Company HR,QuantMagnum Technologies Pvt. Ltd.,UK - (london)
15,Vaishnavi Kudalkar,HR Executive,Codeachive learning,Abhishek - Only Analytics Hiring - India and
16,Kapil Devang,HR Manager,BISP Solutions,Recruitment Lead Consultant
17,Sakshi Chhikara,Assistant Manager HR,BIZ INFOTECNO PRIVATE LIMITED,Vadodara / Baroda
18,Ruchi Dhote,Senior Executive Talent Acquisition,Bristlecone India Ltd,Institute for Financial Management and Resear
19,Manisha Yadav,HR Executive,Easi Tax,Programme Manager
20,Riya Rajesh,Manager Talent Acquisition,Novelworx Digital Solutions,Chennai
21,Rashmi Bhattacharjee,HR Head,AXESTRACK SOFTWARE SOLUTIONS PRIVATE...,Balu Ramesh
22,Faizan Kareem,HR MANAGER,FirstTech Consaltants Pvt.Ltd,HR Administrator
23,Rithika dadwal,HR Recruiter,Affine Analytics,Trivandrum
24,Sandhya Khandagale,HR Recruiter,Compumatrice Multimedia Pvt Ltd,Asif Lucknowi
25,Shaun Rao,Manager Human Resources,Exela Technologies,Director
26,Azahar Shaikh,Company Recruiter,NEAL ANALYTICS SERVICES PVT LTD,Indore
27,Manas,Lead Talent acquisition,Autumn Leaf Consulting Services Private...,InstaFinancials
28,kumar,Proprietor,trainin,Human Resource
29,Sunil Vedula,CEO,Nanoprecise Sci Corp,Bengaluru / Bangalore
30,Rajat Kumar,Founder CEO,R.S Consultancy &amp; Services,Mahesh Babu Channa
31,Dhruv Dev Dubey,Company Recruitment Head,Confidential,HR Team Lead
32,Jayanth N,Project Manager,"Dollarbird Information Services Pvt, Ltd",Hyderabad / Secunderabad
33,Avodha,Business Development Associate,Nikitha Palaparthi,Priyanka Akiri
34,Priya Khare,Senior Manager,Independent Consultant,HR Manager
35,Amit Sharma,Consultant,ASCO consulting,Hyderabad
36,Kanan,senior technology instructor,NY INST,Kalpana Dumpala
37,Shashikant Chaudhary,HR Recruiter/HR Excutive,3D India Staffing Research &amp; Consulting...,Executive Hiring
38,Brad,"Manager, Technical Recruiting",O.C. Tanner,Hyderabad / Secunderabad
39,Rutuja Pawar,Technical Recruiter,Demand Matrix,Mubarak
40,Madhusudhan Sridhar,Erp Implementer,MADHUSUDHAN SRIDHAR,Company HR
41,Ankit Sinha,Head Analytics,Suntech Global,Bengaluru / Bangalore
42,Gaurav Chouhan,Chief Technical Officer,Strategic Consulting Lab,Kushal Rastogi
43,Rashi Kacker,Sr Product Manager,Impel Labs Pvt. Ltd.,Company HR
44,Ashwini,Director Global Delivery,MRP Advisers,Mumbai
45,Balaji Kolli,Co Founder,Saras Solutions India Pvt Ltd,Vaishnavi Kudalkar
46,Rajani Nagaraj,HR Manager,WildJasmine,HR Executive
47,ROHIT Kumar,Architect,LNT Private Limited,Mumbai
48,Amir Chowdhury,Managing Partner,Granular.ai,Kapil Devang
49,Daniel Vaz,Partner,Aquis Search,HR Manager

Q 8) Scrape the details of Highest selling novels. Url = https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare/

You have to find the following details:

A) Book name

B) Author name

C) Volumes sold

D) Publisher

E) Genre

In [11]:
# Connecting to the webdriver
driver=webdriver.Chrome(r"C:\Chrome driver\Chromedriver.exe")
driver.maximize_window()

In [12]:
# Getting the webpage of mentioned url 
driver.get(" https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare/")

In [13]:
# ceate empty list to store the details
book = []
author = []
volume = []
publisher = []
genre = []

In [15]:
# Book_name
for i in driver.find_elements(By.XPATH,"//div[@class='embed block']/table/tbody/tr/td[2]"):
    book.append(i.text)
# Author_name
for j in driver.find_elements(By.XPATH,"//div[@class='embed block']/table/tbody/tr/td[3]"):
    author.append(j.text)
# Volumes sold
for k in driver.find_elements(By.XPATH,"//div[@class='embed block']/table/tbody/tr/td[4]"):
    volume.append(k.text)
# Publisher
for l in driver.find_elements(By.XPATH,"//div[@class='embed block']/table/tbody/tr/td[5]"):
    publisher.append(l.text)
# Genre
for m in driver.find_elements(By.XPATH,"//div[@class='embed block']/table/tbody/tr/td[6]"):
    genre.append(m.text)

In [16]:
# Create Dataframe
df=pd.DataFrame({})
df["Book Name"]=book
df["Author name"]=author
df["Volumes sold"]=volume
df["Publisher"]=publisher
df["Genre"]=genre
df

,Book Name,Author name,Volumes sold,Publisher,Genre
0,"Da Vinci Code,The","Brown, Dan","5,094,805",Transworld,"Crime, Thriller & Adventure"
1,Harry Potter and the Deathly Hallows,"Rowling, J.K.","4,475,152",Bloomsbury,Children's Fiction
2,Harry Potter and the Philosopher's Stone,"Rowling, J.K.","4,200,654",Bloomsbury,Children's Fiction
3,Harry Potter and the Order of the Phoenix,"Rowling, J.K.","4,179,479",Bloomsbury,Children's Fiction
4,Fifty Shades of Grey,"James, E. L.","3,758,936",Random House,Romance & Sagas
...,...,...,...,...,...
95,"Ghost,The","Harris, Robert","807,311",Random House,General & Literary Fiction
96,Happy Days with the Naked Chef,"Oliver, Jamie","794,201",Penguin,Food & Drink: General
97,"Hunger Games,The:Hunger Games Trilogy","Collins, Suzanne","792,187",Scholastic Ltd.,Young Adult Fiction
98,"Lost Boy,The:A Foster Child's Search for the L...","Pelzer, Dave","791,507",Orion,Biography: General
99,Jamie's Ministry of Food:Anyone Can Learn to C...,"Oliver, Jamie","791,095",Penguin,Food & Drink: General

In [17]:
driver.close()

# 9. Scrape the details most watched tv series of all time from imdb.com.

Url = https://www.imdb.com/list/ls095964455/

You have to find the following details:

A) Name

B) Year span

C) Genre

D) Run time

E) Ratings

F) Votes

In [3]:
# Connecting to the webdriver
driver=webdriver.Chrome(r"C:\Chrome driver\Chromedriver.exe")
driver.maximize_window()

In [4]:
# Getting the webpage of mentioned url 
driver.get("https://www.imdb.com/list/ls095964455/")

In [5]:
name = []
year = []
genre = []
run_time = []
ratings = []
votes = []

In [7]:
# Name
for i in driver.find_elements(By.XPATH,"//div[@class='lister-item-content']/h3/a"):
    name.append(i.text)
# Year
for j in driver.find_elements(By.XPATH,"//div[@class='lister-item-content']/h3/span[2]"):
    year.append(j.text)
# Genre
for k in driver.find_elements(By.XPATH,"//div[@class='lister-item-content']/p/span[5]"):
    genre.append(k.text)
# Run Time
for l in driver.find_elements(By.XPATH,"//div[@class='lister-item-content']/p/span[3]"):
    run_time.append(l.text)
# Votes
for n in driver.find_elements(By.XPATH,"//div[@class='lister-item-content']/div[1]/div/span[2]"):
    ratings.append(n.text)
# Ratings
for m in driver.find_elements(By.XPATH,"//div[@class='lister-item-content']/p[4]/span[2]"):
    votes.append(m.text)

In [8]:
# Creating Dataframe
df = pd.DataFrame({})
df["Name"] = name
df["Year span"] = year
df["Genre"] = genre
df["Run time"] = run_time
df["Ratings"] = ratings
df["Votes"] = votes
df

,Name,Year span,Genre,Run time,Ratings,Votes
0,Game of Thrones,(2011–2019),"Action, Adventure, Drama",57 min,9.2,"2,059,399"
1,Stranger Things,(2016– ),"Drama, Fantasy, Horror",51 min,8.7,"1,153,417"
2,The Walking Dead,(2010–2022),"Drama, Horror, Thriller",44 min,8.1,"971,492"
3,13 Reasons Why,(2017–2020),"Drama, Mystery, Thriller",60 min,7.5,"289,703"
4,The 100,(2014–2020),"Drama, Mystery, Sci-Fi",43 min,7.6,"249,157"
...,...,...,...,...,...,...
95,Reign,(2013–2017),Drama,42 min,7.4,"49,669"
96,A Series of Unfortunate Events,(2017–2019),"Adventure, Comedy, Drama",50 min,7.8,"60,709"
97,Criminal Minds,(2005–2020),"Crime, Drama, Mystery",42 min,8.1,"195,396"
98,Scream: The TV Series,(2015–2019),"Comedy, Crime, Drama",45 min,7.1,"41,124"
99,The Haunting of Hill House,(2018),"Drama, Horror, Mystery",572 min,8.6,"237,824"

In [9]:
driver.close()

# 10. Details of Datasets from UCI machine learning repositories.

Url = https://archive.ics.uci.edu/
You have to find the following details:

A) Dataset name

B) Data type

C) Task

D) Attribute type

E) No of instances

F) No of attribute

G) Year

Note: - from the home page you have to go to the ShowAllDataset page through code.

In [2]:
# Connecting to the webdriver
driver=webdriver.Chrome(r"C:\Chrome driver\Chromedriver.exe")
driver.maximize_window()

In [3]:
# Getting the webpage of mentioned url 
driver.get("https://archive.ics.uci.edu/")

In [10]:
# fetching view all dataset button from the webpage
viewall_dataset = driver.find_element(By.XPATH,"//tbody[1]//tr/td[2]/span[2]/a")
page_url = viewall_dataset.get_attribute("href")
driver.get(page_url)
time.sleep(3)

In [11]:
# fetching page urls of all datasets
view_list = driver.find_element(By.XPATH,"/html/body/table[2]/tbody/tr/td[2]/table[1]/tbody/tr/td[2]/p/a")
list_url = view_list.get_attribute("href")
driver.get(list_url)
time.sleep(3)

In [13]:
# fetching urls for each dataset
dataset_url = driver.find_elements(By.XPATH,"//p[@class='normal']//b/a")

urls = []
for i in dataset_url:
    urls.append(i.get_attribute("href"))

In [ ]:
# creating empty lists
Dataset_name = []
Data_type = []
Task = []
Attribute_type = []
No_of_instances = []
No_of_attributes = []
Year = []

for i in urls:
    driver.get(i)
    time.sleep(3)
    
    
    # scraping  Dataset name
    try:
        dataset_name = driver.find_element_by_xpath("//span[@class='heading']")
        Dataset_name.append(dataset_name.text)
    except NoSuchElementException:
        Dataset_name.append('-')
    time.sleep(3)
    
    
    
    # scraping data type
    try:
        data_type = driver.find_element_by_xpath("//table[@border='1']//tbody/tr/td[2]")
        if data_type.text == "N/A": raise NoSuchElementException
        Data_type.append(data_type.text)
    except NoSuchElementException:
        Data_type.append('-')
    time.sleep(3)
    
    
    # scraping Task
    try:
        task = driver.find_element_by_xpath("//table[@border='1']//tbody/tr[3]/td[2]")
        if task.text == "N/A": raise NoSuchElementException
        Task.append(task.text)
    except NoSuchElementException:
        Task.append('-')
    time.sleep(3)
    
    
    
    # scraping Attribute type
    try:
        attribute_type = driver.find_element_by_xpath("//table[@border='1']//tbody/tr[2]/td[2]")
        if attribute_type.text == "N/A": raise NoSuchElementException
        Attribute_type.append(attribute_type.text)
    except NoSuchElementException:
        Attribute_type.append('-')
    time.sleep(3)
    
    
    
    # scraping No of Instances
    try:
        instances = driver.find_element_by_xpath("//table[@border='1']//tbody/tr/td[4]")
        if instances.text == "N/A": raise NoSuchElementException
        No_of_instances.append(instances.text)
    except NoSuchElementException:
        No_of_instances.append('-')
    time.sleep(3)
    
    
    
    # scraping No of Arrtibutes
    try:
        attribute = driver.find_element_by_xpath("//table[@border='1']//tbody/tr[2]/td[4]")
        if attribute.text == "N/A": raise NoSuchElementException
        No_of_attributes.append(attribute.text)
    except NoSuchElementException:
        No_of_attributes.append('-')
    time.sleep(3)
    
    
    # scraping Year
    try:
        year = driver.find_element_by_xpath("//table[@border='1']//tbody/tr[2]/td[6]")
        if year.text == "N/A": raise NoSuchElementException
        Year.append(year.text[:4])
    except NoSuchElementException:
        Year.append('-')
    time.sleep(3)

In [ ]:
#DATA FRAMEING
UCI=pd.DataFrame({})
UCI['Data Name'] = Data_name
UCI['Data Type'] = Data_type
UCI['Task'] = Task
UCI['Attribute type'] = Attr_type
UCI['No of instance'] = Instances
UCI['No of attributes'] = n_attributes
UCI['Year'] = Year
UCI